# Generated by Django 5.0.6 on 2026-09-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0024_add_tipo_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariovinculo',
            name='motivo_saida',
            field=models.CharField(blank=True, choices=[('transferencia', 'Transferência'), ('rescisao_indireta', 'Rescisão indireta'), ('rescisao_experiencia_antecipado_empregador', 'Rescisão experiencia antecipado empregador'), ('rescisao_experiencia_antecipado_trabalhador', 'Rescisão experiencia antecipado trabalhador'), ('rescisao_termino_contrato_experiencia', 'Rescisão termino contrato experiencia'), ('rescisao_acordo', 'Rescisão acordo'), ('termino_contrato', 'Término de contrato'), ('pedido_demissao', 'Pedido de demissão'), ('demissao_sem_justa_causa', 'Demissão sem justa causa'), ('demissao_justa_causa', 'Demissão por justa causa'), ('outro', 'Outro')], max_length=50, null=True),
        ),
    ]
